name: Eleven Workflow
on: [push]
jobs:
    run-first-command:
        runs-on: ubuntu-latest
        environment: "staging"
        steps:
            - name: Our secrets and vars
              run: |
                  echo '${{ vars.STATUS }}'
                  echo '${{ secrets.PASSWORD }}'
