name: Fourth workflow
on:
    workflow_run:
        workflows: [Third workflow]
        types:
            - completed

jobs:
    hello-command:
        runs-on: ubuntu-latest
        steps:
            - name: Say hello
              run: echo "Hello"
