name: Six workflow
on:
  push: 
    branches: 
      - main
      - about  
    # tags: 
    #   - "v1" 
    paths: 
      - "**.html"       
jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Event Vars
        run: echo $GITHUB_SHA
          echo $GITHUB_REF
