name: Tenth workflow
on: [push]
jobs:
  run-first-command:
    runs-on: ubuntu-latest
    environment: "production"
    steps:
      - name: Our secrets and vars
        run: |
          echo '${{ vars.STATUS }}'
          echo '${{ secrets.PASSWORD }}'
          

 