name: Third workflow
on: [push]

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
            - name: Command in Multiline
              run: |
                  pwd
                  1s -a
    
