name: Third workflow
on: [push]

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
            - name: List files and Copy Repo
              run: 
                  1s -a
            - uses: actions/checkout@v4
            - name: List files
              run: 
                  1s -a
    
